//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceClothShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDiscount
    {
        public int ProductDiscountID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public decimal DiscountAmount { get; set; }
        public bool IsPercentage { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
